-- 코드를 입력하세요
SELECT
    PRODUCT_CODE,
    PRICE*SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT PR
    INNER JOIN OFFLINE_SALE OS
    ON PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;

